backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
logo_url: https://doggoland.cz/pics/logo.png
locale: 'cs'

collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "src/pages/aktuality"
    create: true
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Obrázek", name: "image", widget: "image", required: false}
      - { name: "body", label: "Text aktuality", widget: "markdown" }
      - { label: "Datum publikace (pro řazení)", name: "date", widget: "datetime" }
      - {
          name: "templateKey",
          widget: "hidden",
          default: "aktuality"
        }
  - name: "authors"
    label: "Autoři"
    folder: "src/pages/authors"
    create: true
    fields:
      - { label: "Jméno autora", name: "title", widget: "string" }
      - { label: "Fotka autora", name: "image", widget: "image" }
      - {
          name: "templateKey",
          widget: "hidden",
          default: "author"
        }
  - name: "harmonogram-akce"
    label: "Konané akce"
    folder: "src/pages/harmonogram"
    create: true
    fields:
      - { name: "templateKey", widget: "hidden", default: "harmonogram-akce" }
      - { name: "title", label: "Název akce", widget: "string" }
      - { label: "Datum konání akce", name: "date", widget: "datetime" }
      - { name: "body", label: "Popis akce", widget: "markdown" }
  - name: "psi-v-nasi-peci"
    label: "Psi v naší péči"
    folder: "src/pages/psi-v-nasi-peci"
    create: true
    fields:
      - { name: "templateKey", widget: "hidden", default: "psi-v-nasi-peci" }
      - { name: "title", label: "Jméno psa v naší péči", widget: "string" }
      - { name: "description", label: "Popis psa v naší péči", widget: "text" }
      - { label: "Obrázek psa", name: "featuredimage", widget: image }
  - name: "adoptovani-psi"
    label: "Adoptovaní psi"
    folder: "src/pages/adoptovani-psi"
    create: true
    fields:
      - { name: "templateKey", widget: "hidden", default: "adoptovani-psi" }
      - { name: "title", label: "Jméno adoptovaného psa", widget: "string" }
      - { label: "Obrázek adoptovaného psa", name: "featuredimage", widget: image }
  - name: "slevy"
    label: "Slevy a sponzoři"
    folder: "src/pages/slevy"
    create: true
    fields:
      - { name: "templateKey", widget: "hidden", default: "slevy" }
      - { name: "title", label: "Jméno sponzora", widget: "string" }
      - { name: "discount", label: "Míra slevy", widget: "text" }
      - { name: "code", label: "Slevový kód", widget: "text" }
      - { name: "website", label: "Webové stránky sponzora", widget: "text" }
      - { name: "body", label: "Popis slevy", widget: "markdown" }
      - { name: "featuredimage", label: "Logo sponzora", widget: "image" }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Datum publikace", name: "date", widget: "datetime" }
      - { label: "Úvodní obrázek (na titulce)", name: "featuredimage", widget: image }
      - { label: "Text (obrázek na začátek nebo kousek dál, ale určitě dávat)", name: "body", widget: "markdown" }
      - { label: "Tagy", name: "tags", widget: "list" }
      - { label: Popis (meta tag), name: description, widget: string }
      - {
        label: "Autor článku",
        name: "author",
        widget: "relation",
        collection: "authors",
        search_fields: ["title"],
        value_field: "title",
        display_fields: ["title"]
        }


  - name: "adopce"
    label: "Adopce"
    folder: "src/pages/adopce"
    create: true
    slug: "{{slug}}"
    fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "adopce-post",
            }
          - { label: "Obrázek na stránce adopcí", name: "featuredimage", widget: image }
          - { label: "Úvodní obrázek", name: image, widget: image }
          - { label: "Titulní nadpis", name: title, widget: string }
          - { label: "Nadpis nad textovou kostrou", name: heading, widget: string }
          - { label: "Textová kostra", name: "body", widget: "markdown" }
          - {
              label: "Galerie obrázků",
              name: intro,
              widget: object,
              fields:
                [
                  {
                    label: Obrázky,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Obrázek, name: image, widget: image },
                      ],
                  },
                ],
            }
          - { label: Popis na stránku adopcí, name: description, widget: string }


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
